---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install a list of packages required for PHP 
  apt: 
    name: "{{item}}"
    state: present
  with_items:
     - apt-transport-https
     - ca-certificates
     - software-properties-common
     - gpg

- name: import the PHP apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: install PHP deb repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: Install a list of packages for PHP  #magento-2-php-extensions
  apt: 
    name: "{{item}}"
    state: present
  with_items:
     - php8.2
     - php8.2-gd
     - php8.2-mcrypt
     - php8.2-curl
     - php8.2-intl
     - php8.2-xsl
     - php8.2-mbstring
     - php8.2-zip
     - php8.2-soap
     - php8.2-bcmath
     - php8.2-ctype
     - php8.2-dom
     - php8.2-iconv
     - php8.2-simplexml
     - php8.2-sockets
     - php8.2-cli
     - php8.2-fpm
     - php8.2-xml
     - php8.2-redis
     - php8.2-enchant
     - php8.2-mysql
     - php8.2-cgi
     - php8.2-common
     - php8.2-opcache
     - php8.2-readline
     - php8.2-memcached
     - php8.2-bz2
     - php-tcpdf   
     - unzip
     - wget
     - git
     - aptitude

# - name: Composer download
#   ansible.builtin.shell: curl -sS https://getcomposer.org/installer |php

# - name: Composer install
#   ansible.builtin.shell: mv composer.phar /usr/local/bin/composer

# - name: Composer permissions
#   file: dest=/usr/local/bin/composer mode=a+x



