---
- name: remove apache2 which is installed by default
  become: true
  apt:
    name: apache2
    state: absent     #process bound to the HTTP port 80.

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/CN=magento' -days 365
    -newkey rsa:4096 -sha256 -keyout {{ item.key }} -out {{ item.cert }}
    creates={{ item.cert }}
  with_items: "{{ self_signed_certs }}"

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present 

- name: copy default.j2
  tags: server:settings
  template:
     src: default.j2
     dest: '/etc/nginx/sites-available/default'
  notify: restart nginx

- name: copy nginx conf
  tags: server:settings
  template:
     src: nginx.conf.j2
     dest: '/etc/nginx/nginx.conf'
  notify: restart nginx