---
- name: remove apache2 which is installed by default
  become: true
  apt:
    name: apache2
    state: absent     #process bound to the HTTP port 80.

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present 
