---
# - name: remove apache2 which is installed by default
#   become: true
#   apt:
#     name: apache2
#     state: absent

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present 

- name: Remove existing cert
  command: rm -rf /etc/nginx/server.crt

- name: Remove existing key
  command: rm -rf /etc/nginx/server.key

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=DE/ST=Berlin/L=Berlin/O=IT/CN=Ansible" -days 3650 -keyout /etc/nginx/server.key -out /etc/nginx/server.crt -extensions v3_ca creates=/etc/nginx/server.crt

- name: copy default.j2
  tags: server:settings
  template:
     src: default.j2
     dest: '/etc/nginx/sites-available/default'
  notify: restart nginx

- name: copy nginx conf
  tags: server:settings
  template:
     src: nginx.conf.j2
     dest: '/etc/nginx/nginx.conf'
  notify: restart nginx

- name: Change file ownership of socket file 
  ansible.builtin.file:
    path: /var/run/php/php8.2-fpm.sock
    owner: test-ssh
    group: clp
  notify: restart nginx
