- hosts: web-servers
  become: true
  roles:
  - role: users
    tags: create user "test-ssh"  # create user
  - role: install_php
    tags: install,php,8.2         # php
  - role: php_fpm
    tags: install,php-fpm         # php-fpm
  - role: mysql
    tags: mysql, install         # mysql
  - role: nginx
    tags: install, nginx           # nginx
  - role: elasticsearch   
    tags: install, elasticsearch   # elasticsearch
  - role: redis
    tags: install, redis           # redis
  - role: magento2
    tags: magento2                # magento2
  - role: varnish
    tags: install, varnish         # varnish
  - role: phpmyadmin
    tags: install, phpmyadmin      # phpmyadmin
  - role: codedeploy-agent
    tags: codedeploy-agent, deploy-agent