---

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: Install php-twig, required dependency for phpMyAdmin
  ansible.builtin.shell: yes | aptitude -t buster-backports install php-twig
  args:
    executable: /bin/bash

- name: install PhpMyAdmin
  apt: pkg=phpmyadmin state=present

- name: configure site
  file: path=/var/www/html/pub/phpmyadmin src=/usr/share/phpmyadmin state=link


- name: Change file ownership 
  ansible.builtin.file:
    path: /var/www/html/pub/phpmyadmin/
    state: directory
    owner: test-ssh
    group: clp
    recurse: yes

- name: Change file ownership to origin
  ansible.builtin.file:
    path: /usr/share/phpmyadmin/
    state: directory
    owner: test-ssh
    group: clp
    recurse: yes

- name: Change file ownership of sock file
  ansible.builtin.file:
    path: /var/run/php/php8.2-fpm.sock
    mode: '0777'