---



- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www/html/phpMyAdmin
    state: directory
    mode: '0755'

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/5.1.1/phpMyAdmin-5.1.1-all-languages.tar.gz
    dest: /var/www/html/phpMyAdmin
    remote_src: yes

- name: copy conf file
  tags: server:settings
  template:
     src: inc.php.j2
     dest: '/var/www/html/phpMyAdmin/config.inc.php'

- name: Change file ownership 
  ansible.builtin.file:
    path: /var/www/html/phpMyAdmin
    state: directory
    owner: test-ssh
    group: clp
    recurse: yes

- name: Change file permissions
  ansible.builtin.file:
    path: /var/www/html/phpMyAdmin/config.inc.php
    mode: '0660'