---

- name: Install Varnish
  become: true
  apt:
    name: varnish
    state: present 

- name: copy vcl file
  tags: server:settings
  template:
     src: default.vcl.j2
     dest: '/etc/varnish/default.vcl'
  notify: restart varnish
    
- name: Load default.vcl
  ansible.builtin.shell: varnishadm vcl.load default /etc/varnish/default.vcl
  ignore_errors: yes

- name: Activate default.vcl
  ansible.builtin.shell: varnishadm vcl.use default