---

 - name: Install a list of packages for PHP
   apt: name={{item}} state=installed
   with_items:
     - apt-transport-https
     - ca-certificates
     - software-properties-common


- name: import the PHP apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  become: true

- name: install PHP deb repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ $(lsb_release -sc) main
    state: present
  become: true

- name: install PHP
  apt:
    name: php7.4
    state: present
    update_cache: true
  loop:
    - openjdk-8-jre-headless
    - php7.4
  become: true
