---
- name: Download file from a file path
  shell: wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb -P /usr/local/bin/

- name: Install GNUPG
  apt:
    name: gnupg
    state: present

- name: mysql-apt-config
  apt: 
   deb: "/usr/local/bin/mysql-apt-config_0.8.13-1_all.deb"

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: B7B3B788A8D3785C

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{server_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{server_password | quote}}' vtype='password'
  become: true

- name: Install server
  apt:
    name: mysql-server
    state: present
  notify: restart-mysql

- name: Install mysql client
  apt:
    name: mysql-client
    state: present
  

- name: Install python3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Make sure pymysql is present
  apt:
    name: python3-mysqldb
    state: present

- name: Install a .deb package from the internet
  apt:
    deb: http://ftp.us.debian.org/debian/pool/main/p/python-pymysql/python-pymysql_0.9.3-1_all.deb

# - name: Update mysql root password for all root accounts "{{ server_password }}"
#   mysql_user: name=root password="{{ server_password }}" priv="*.*:ALL,GRANT"

- name: copy my.cnf
  tags: server:settings
  template:
     src: my.cnf.j2
     dest: '/etc/mysql/my.cnf'
  notify: restart-mysql


- name: Create new database with names 'magento'
  tags: "mysql::db"
  mysql_db:
    name: magento
    state: present
    login_user: "{{ server_user }}"
    login_password: "{{ server_password }}"
  run_once: true    

- name: Create new database with names 'PhpMyAdmin'
  tags: "mysql::db"
  mysql_db:
    name: phpmyadmin
    state: present
    login_user: "{{ server_user }}"
    login_password: "{{ server_password }}"
  run_once: true    

- name: Create database user with name 'magento-user'
  tags: "mysql::user"
  mysql_user:
    name: magento-user
    password: 6x5UE8dp5337Yc
    priv: "*.*:ALL"
    state: present
    login_user: "{{ server_user }}"
    login_password: "{{ server_password }}"
  run_once: true    

- name: Create database user for 'phpmyadmin'
  tags: "mysql::user"
  mysql_user:
    name: phpmyadmin
    password: 6x5UE8dp5337Yc
    priv: "*.*:ALL"
    state: present
    login_user: "{{ server_user }}"
    login_password: "{{ server_password }}"
  run_once: true    