---
- name: import the elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install elasticsearch 7.x deb repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: install jessie backports
  apt_repository:
    repo: 'deb http://security.debian.org/debian-security stretch/updates main'
    state: present

- name: Install package
  ansible.builtin.shell: apt-get install -y openjdk-8-jdk
  args:
    chdir: /var/www/html/
    executable: /bin/bash
    warn: false

- name: install elasticsearch 7.x
  apt:
    name: elasticsearch
    state: present
    update_cache: true
  loop:
    - elasticsearch
    - kibana

- name: start ES
  systemd:
    name: elasticsearch.service
    state: started
