---
- name: import the elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install elasticsearch 7.x deb repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install ElasticSearch server and Kibana for viewing data.
  apt: 
    name: "{{item}}"
    state: present
  with_items:
     - elasticsearch
     - kibana

- name: start elasticsearch service
  systemd:
    name: elasticsearch.service
    state: restarted
